name: Test QCode Chat Extension

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16, 18, 20]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install Dependencies
      run: |
        npm ci
        
    - name: Compile Extension
      run: |
        npm run compile
        
    - name: Run Linter
      run: |
        npm run lint
      continue-on-error: true
      
    - name: Run Unit Tests
      run: |
        npm test
      continue-on-error: true
      
    - name: Validate Package
      run: |
        npm install -g @vscode/vsce
        vsce package --dry-run
        
    - name: Test Installation
      run: |
        # Test that package can be installed (without actually installing)
        echo "Testing installation process..."
        npm pack
        ls -la *.tgz
